#!/usr/bin/env python3
"""Export known Brugopeningen bridges from a running HA instance.

Reads the HA device registry and outputs a ready-to-paste BRIDGE_NAMES dict
for use in custom_components/brugopen/bridge_names.py.

Usage (on the HA host, HA does NOT need to be stopped):
    python3 export_bridge_names.py
    python3 export_bridge_names.py --config /path/to/config   # non-default path
    python3 export_bridge_names.py --out ../custom_components/brugopen/bridge_names.py

The --out flag overwrites bridge_names.py directly.  Without it the dict is
printed to stdout so you can review and copy-paste manually.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys


HEADER = '''\
"""Static translation table: bridge location code → human-readable name.

The NDW brugopeningen feed does not include bridge names in the XML.
This file maps the stable bridge location codes (derived from the DATEX II
situation/@id by stripping the trailing event counter) to friendly names.

Rename bridges via Settings → Devices & Services → Brugopeningen → the device.
This file is auto-generated by tools/export_bridge_names.py – feel free to
edit the names manually afterwards.
"""

'''


def load_devices(config_dir: pathlib.Path) -> list[dict]:
    registry_path = config_dir / ".storage" / "core.device_registry"
    if not registry_path.exists():
        sys.exit(f"Device registry not found at {registry_path}")
    data = json.loads(registry_path.read_text())
    # HA 2023+ stores devices under data.devices
    return data.get("data", {}).get("devices", [])


def _location_code(bridge_id: str) -> str:
    """Strip the prefix (e.g. MOS01_) from a bridge_id."""
    _, _, code = bridge_id.partition("_")
    return code if code else bridge_id


def extract_bridges(devices: list[dict]) -> dict[str, str]:
    """Return {bridge_id: friendly_name} for all brugopen devices."""
    bridges: dict[str, str] = {}
    for device in devices:
        identifiers = device.get("identifiers", [])
        for entry in identifiers:
            # identifiers is a list of [domain, value] pairs
            if len(entry) == 2 and entry[0] == "brugopen":
                bridge_id: str = entry[1]
                loc_code = _location_code(bridge_id)
                # Prefer name set by user, fall back to auto-generated name
                name: str = (
                    device.get("name_by_user")
                    or device.get("name")
                    or bridge_id
                )
                bridges[loc_code] = name
    return bridges


def render(bridges: dict[str, str]) -> str:
    lines = [f'    "{bid}": "{name}",' for bid, name in sorted(bridges.items())]
    body = "\n".join(lines)
    return HEADER + f"BRIDGE_NAMES: dict[str, str] = {{\n{body}\n}}\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        default="/config",
        help="Path to HA config directory (default: /config)",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Write output directly to this file instead of stdout",
    )
    args = parser.parse_args()

    config_dir = pathlib.Path(args.config)
    devices = load_devices(config_dir)
    bridges = extract_bridges(devices)

    if not bridges:
        sys.exit(
            "No brugopen devices found in the device registry.\n"
            "Make sure the integration has run at least one poll cycle."
        )

    output = render(bridges)

    if args.out:
        out_path = pathlib.Path(args.out)
        out_path.write_text(output)
        print(f"Wrote {len(bridges)} bridges to {out_path}")
    else:
        print(output)
        print(f"# {len(bridges)} bridges exported", file=sys.stderr)


if __name__ == "__main__":
    main()
