#!/usr/bin/env python3
"""Look up bridge names and provinces via OpenStreetMap (Overpass API).

Reads all bridges known to the integration from HA's .storage file
(brugopen.bridges), then queries the Overpass API for the nearest named
bridge object and the province it lies in.

Output: a ready-to-use bridge_names.py.

Usage:
    # preview to stdout:
    python3 tools/lookup_bridge_names.py

    # write directly to bridge_names.py:
    python3 tools/lookup_bridge_names.py \
        --out custom_components/brugopen/bridge_names.py

    # non-default HA config path:
    python3 tools/lookup_bridge_names.py --config /path/to/config

Notes
-----
- Overpass queries are batched and rate-limited (1 req/s).  Expect ~1 minute
  for every 60 bridges.
- Bridges with no nearby OSM name get the bare location code as name.
- The script does NOT need HA to be running.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import time
import urllib.request
import urllib.parse
from typing import Optional


OVERPASS_URL = "https://overpass-api.de/api/interpreter"
SEARCH_RADIUS_M = 100   # metres around bridge coordinates to search for OSM name
PROVINCE_RADIUS_M = 500  # fallback search radius for province name
RATE_LIMIT_S = 1.0       # seconds between Overpass requests

HEADER = '''\
"""Static translation table: bridge location code → human-readable name.

The NDW brugopeningen feed does not include bridge names in the XML.
This file maps the location code portion of a bridge ID to a friendly name
in the format  "Province - Bridge name".

Auto-generated by tools/lookup_bridge_names.py using OpenStreetMap data.
Edit manually to correct or add entries.
"""

'''


# ---------------------------------------------------------------------------
# Storage helpers
# ---------------------------------------------------------------------------

def _location_code(bridge_id: str) -> str:
    _, _, code = bridge_id.partition("_")
    return code if code else bridge_id


def load_bridges(config_dir: pathlib.Path) -> list[dict]:
    """Return list of bridge dicts from HA's brugopen.bridges storage file."""
    storage = config_dir / ".storage" / "brugopen.bridges"
    if not storage.exists():
        sys.exit(
            f"Storage file not found: {storage}\n"
            "Make sure the integration has run at least one poll cycle."
        )
    data = json.loads(storage.read_text())
    return data.get("data", {}).get("bridges", [])


# ---------------------------------------------------------------------------
# Overpass helpers
# ---------------------------------------------------------------------------

def _overpass(query: str) -> dict:
    """Execute an Overpass QL query and return the parsed JSON response."""
    encoded = urllib.parse.urlencode({"data": query}).encode()
    req = urllib.request.Request(
        OVERPASS_URL,
        data=encoded,
        headers={"User-Agent": "brugopen-lookup/1.0"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def osm_bridge_name(lat: float, lon: float) -> Optional[str]:
    """Return the name of the nearest movable bridge in OSM, or None."""
    query = f"""
[out:json][timeout:10];
(
  node["bridge:movable"](around:{SEARCH_RADIUS_M},{lat},{lon});
  way["bridge:movable"](around:{SEARCH_RADIUS_M},{lat},{lon});
  node["bridge"="movable"](around:{SEARCH_RADIUS_M},{lat},{lon});
  way["bridge"="movable"](around:{SEARCH_RADIUS_M},{lat},{lon});
  node["man_made"="bridge"](around:{SEARCH_RADIUS_M},{lat},{lon});
  way["man_made"="bridge"](around:{SEARCH_RADIUS_M},{lat},{lon});
);
out tags 1;
"""
    try:
        result = _overpass(query)
        for element in result.get("elements", []):
            name = element.get("tags", {}).get("name")
            if name:
                return name
    except Exception as exc:
        print(f"  [warn] Overpass error: {exc}", file=sys.stderr)
    return None


def osm_province(lat: float, lon: float) -> Optional[str]:
    """Return the Dutch province name for given coordinates."""
    query = f"""
[out:json][timeout:10];
is_in({lat},{lon})->.a;
rel(pivot.a)["admin_level"="4"]["boundary"="administrative"];
out tags 1;
"""
    try:
        result = _overpass(query)
        for element in result.get("elements", []):
            name = element.get("tags", {}).get("name")
            if name:
                return name
    except Exception as exc:
        print(f"  [warn] Overpass province error: {exc}", file=sys.stderr)
    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="/config",
                        help="Path to HA config directory (default: /config)")
    parser.add_argument("--out", default=None,
                        help="Write output to this file instead of stdout")
    parser.add_argument("--radius", type=int, default=SEARCH_RADIUS_M,
                        help=f"OSM search radius in metres (default: {SEARCH_RADIUS_M})")
    args = parser.parse_args()

    config_dir = pathlib.Path(args.config)
    bridges = load_bridges(config_dir)

    if not bridges:
        sys.exit("No bridges found in storage. Run the integration first.")

    # Filter bridges that have coordinates
    with_coords = [b for b in bridges if b.get("latitude") and b.get("longitude")]
    without_coords = [b for b in bridges if not b.get("latitude") or not b.get("longitude")]

    print(f"Found {len(bridges)} bridges, {len(with_coords)} have coordinates.",
          file=sys.stderr)
    if without_coords:
        print(f"{len(without_coords)} bridges have no coordinates – using bare ID.",
              file=sys.stderr)

    results: dict[str, str] = {}

    for i, bridge in enumerate(with_coords, 1):
        bid = bridge["bridge_id"]
        loc = _location_code(bid)
        lat = float(bridge["latitude"])
        lon = float(bridge["longitude"])

        print(f"[{i}/{len(with_coords)}] {loc} @ {lat:.4f},{lon:.4f} ...",
              end=" ", flush=True, file=sys.stderr)

        name = osm_bridge_name(lat, lon)
        time.sleep(RATE_LIMIT_S)

        province = osm_province(lat, lon)
        time.sleep(RATE_LIMIT_S)

        if name and province:
            label = f"{province} - {name}"
        elif name:
            label = name
        elif province:
            label = f"{province} - {loc}"
        else:
            label = loc

        print(label, file=sys.stderr)
        results[loc] = label

    # Bridges without coordinates just use the bare ID
    for bridge in without_coords:
        loc = _location_code(bridge["bridge_id"])
        results[loc] = loc

    # Render output
    lines = [f'    "{k}": "{v}",'
             for k, v in sorted(results.items())]
    body = "\n".join(lines)
    output = HEADER + f"BRIDGE_NAMES: dict[str, str] = {{\n{body}\n}}\n"

    if args.out:
        out_path = pathlib.Path(args.out)
        out_path.write_text(output)
        print(f"\nWrote {len(results)} bridges to {out_path}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
