#!/usr/bin/env python3
"""Look up bridge names using a local bridges.json file.

Reads all bridges known to the integration from HA's .storage file
(brugopen.bridges), matches them against a local bridges.json file by
coordinates, and outputs a ready-to-use bridge_names.py with entries in
the format  "Province - City - Bridge name".

Bridges without a coordinate match fall back to the bare location code.

Usage:
    # preview to stdout:
    python3 tools/lookup_bridge_names.py

    # write directly to bridge_names.py:
    python3 tools/lookup_bridge_names.py \
        --out custom_components/brugopen/bridge_names.py

    # non-default HA config path:
    python3 tools/lookup_bridge_names.py --config /path/to/config

    # non-default bridges.json path:
    python3 tools/lookup_bridge_names.py --bridges tools/bridges.json
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import pathlib
import sys
from typing import Optional


MATCH_RADIUS_M = 150  # metres – coordinate match tolerance

HEADER = '''\
"""Static translation table: bridge location code → human-readable name.

The NDW brugopeningen feed does not include bridge names in the XML.
This file maps the location code portion of a bridge ID to a friendly name
in the format  "Province - City - Bridge name".

Auto-generated by tools/lookup_bridge_names.py using bridges.json data.
Edit manually to correct or add entries.
"""

'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _location_code(bridge_id: str) -> str:
    _, _, code = bridge_id.partition("_")
    return code if code else bridge_id


def _slug_to_name(slug: str) -> str:
    """Convert a URL slug like 'noord-holland' to 'Noord-Holland'."""
    return "-".join(word.capitalize() for word in slug.split("-"))


def _haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Return the distance in metres between two lat/lon points."""
    R = 6_371_000
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlam = math.radians(lon2 - lon1)
    a = (math.sin(dphi / 2) ** 2
         + math.cos(phi1) * math.cos(phi2) * math.sin(dlam / 2) ** 2)
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_existing_names(path: pathlib.Path) -> dict[str, str]:
    """Load BRIDGE_NAMES from an existing bridge_names.py, or return empty dict."""
    if not path.exists():
        return {}
    spec = importlib.util.spec_from_file_location("bridge_names", path)
    mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    try:
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
        return dict(getattr(mod, "BRIDGE_NAMES", {}))
    except Exception as exc:
        print(f"[warn] Could not load existing names from {path}: {exc}", file=sys.stderr)
        return {}


def load_storage_bridges(config_dir: pathlib.Path) -> list[dict]:
    """Return list of bridge dicts from HA's brugopen.bridges storage file."""
    storage = config_dir / ".storage" / "brugopen.bridges"
    if not storage.exists():
        sys.exit(
            f"Storage file not found: {storage}\n"
            "Make sure the integration has run at least one poll cycle."
        )
    data = json.loads(storage.read_text())
    return data.get("data", {}).get("bridges", [])


def load_json_bridges(bridges_path: pathlib.Path) -> list[dict]:
    """Return list of bridge dicts from bridges.json."""
    data = json.loads(bridges_path.read_text())
    return data.get("bridges", [])


# ---------------------------------------------------------------------------
# Matching & formatting
# ---------------------------------------------------------------------------

def find_match(
    lat: float, lon: float, json_bridges: list[dict], max_distance_m: float
) -> Optional[dict]:
    """Return the closest bridge from json_bridges within max_distance_m, or None."""
    best: Optional[dict] = None
    best_dist = max_distance_m
    for b in json_bridges:
        d = _haversine(lat, lon, b["latitude"], b["longitude"])
        if d < best_dist:
            best_dist = d
            best = b
    return best


def bridge_label(match: dict) -> str:
    """Format a bridges.json entry as 'Province - City - Bridge name'."""
    path_parts = match["path"].strip("/").split("/")
    province = _slug_to_name(path_parts[0]) if path_parts else "?"
    city = match.get("city") or (
        _slug_to_name(path_parts[1]) if len(path_parts) > 1 else "?"
    )
    name = match.get("name", "?")
    return f"{province} - {city} - {name}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="/config",
                        help="Path to HA config directory (default: /config)")
    parser.add_argument("--bridges", default=None,
                        help="Path to bridges.json "
                             "(default: bridges.json next to this script)")
    parser.add_argument("--out", default=None,
                        help="Write output to this file instead of stdout")
    parser.add_argument("--existing",
                        default="/config/custom_components/brugopen/bridge_names.py",
                        help="Path to existing bridge_names.py whose entries are kept and "
                             "skipped during lookup "
                             "(default: /config/custom_components/brugopen/bridge_names.py)")
    parser.add_argument("--max-distance", type=float, default=MATCH_RADIUS_M,
                        help=f"Max coordinate match distance in metres "
                             f"(default: {MATCH_RADIUS_M})")
    args = parser.parse_args()

    bridges_path = (
        pathlib.Path(args.bridges)
        if args.bridges
        else pathlib.Path(__file__).parent / "bridges.json"
    )
    if not bridges_path.exists():
        sys.exit(f"bridges.json not found: {bridges_path}")

    config_dir = pathlib.Path(args.config)
    storage_bridges = load_storage_bridges(config_dir)
    json_bridges = load_json_bridges(bridges_path)

    if not storage_bridges:
        sys.exit("No bridges found in storage. Run the integration first.")

    print(f"Loaded {len(json_bridges)} bridges from {bridges_path}.",
          file=sys.stderr)

    # Load existing names and skip bridges that are already known
    existing_names = load_existing_names(pathlib.Path(args.existing))
    if existing_names:
        print(f"Loaded {len(existing_names)} existing names from {args.existing}.",
              file=sys.stderr)

    with_coords = [b for b in storage_bridges
                   if b.get("latitude") and b.get("longitude")]
    without_coords = [b for b in storage_bridges
                      if not b.get("latitude") or not b.get("longitude")]

    print(f"Found {len(storage_bridges)} bridges in storage, "
          f"{len(with_coords)} have coordinates.",
          file=sys.stderr)

    if existing_names:
        with_coords = [b for b in with_coords
                       if _location_code(b["bridge_id"]) not in existing_names]
        without_coords = [b for b in without_coords
                          if _location_code(b["bridge_id"]) not in existing_names]
        skipped = len(storage_bridges) - len(with_coords) - len(without_coords)
        print(f"Skipping {skipped} already-known bridges; "
              f"{len(with_coords) + len(without_coords)} new bridges to look up.",
              file=sys.stderr)

    results: dict[str, str] = dict(existing_names)
    matched = 0

    for bridge in with_coords:
        bid = bridge["bridge_id"]
        loc = _location_code(bid)
        lat = float(bridge["latitude"])
        lon = float(bridge["longitude"])

        match = find_match(lat, lon, json_bridges, args.max_distance)
        if match:
            label = bridge_label(match)
            matched += 1
        else:
            label = loc
            print(f"  [no match] {loc} @ {lat:.4f},{lon:.4f}", file=sys.stderr)

        results[loc] = label

    # Bridges without coordinates fall back to bare location code
    for bridge in without_coords:
        loc = _location_code(bridge["bridge_id"])
        results[loc] = loc

    print(f"Matched {matched}/{len(with_coords)} bridges.", file=sys.stderr)

    lines = [f'    "{k}": "{v}",' for k, v in sorted(results.items())]
    body = "\n".join(lines)
    output = HEADER + f"BRIDGE_NAMES: dict[str, str] = {{\n{body}\n}}\n"

    if args.out:
        out_path = pathlib.Path(args.out)
        out_path.write_text(output)
        print(f"Wrote {len(results)} bridges to {out_path}.", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
